name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Lint code
        run: |
          source venv/bin/activate
          flake8 .

      - name: Test model
        run: |
          source venv/bin/activate
          pytest

      - name: Deploy model
        run: |
          echo "Deploying model (this step can be expanded to include actual deployment commands)"

